### ISSUE TITLE
Using other MNI Spaces

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_abcd#121]
Hello,

I am trying to use this software with fMRIPrep outputs in `MNIPediatricAsym_cohort-1 ` space (T1w-aligned outputs are also available but not of interest). Here is how I run XCP_ABCD on HPC: 
```singularity run -e -B ${scratch}:/workdir -B ${bids_dir} $IMG ${fmriprep_dir} ${output_dir} participant --participant_label ${subject:4} -w /workdir -t Phon --lower-bpf 0.01 --upper-bpf 0.08 -p 36P -f 1 --smoothing 5```

I get the following error after the pybids layout is made: 

```
space not supported
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/cli/run.py", line 455, in build_workflow
    retval['workflow'] = init_xcpabcd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 147, in init_xcpabcd_wf
    single_bold_wf = init_single_bold_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 380, in init_single_bold_wf
    bold_postproc_wf = init_boldpostprocess_wf(bold_file=bold_file,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/bold.py", line 243, in init_boldpostprocess_wf
    fcon_ts_wf = init_fcon_ts_wf(mem_gb=mem_gbx['timeseries'],mni_to_t1w=mni_to_t1w,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/connectivity.py", line 119, in init_fcon_ts_wf
    transformfile = get_transformfile(bold_file=bold_file, mni_to_t1w=mni_to_t1w,
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/utils/utils.py", line 110, in get_transformfile
    return transformfile
UnboundLocalError: local variable 'transformfile' referenced before assignment
```

Do you have any guidance for how to proceed?

Thanks,
Steven

**Comment by a3sha2** [comment]
Hi @smeisler , 
we have not  release post-processing with `MNIPediatricAsym_cohort-1` and `MNIinfant`  spaces that is why. We will release it soon
