### ISSUE TITLE
error message  IndexError: list index out of range

### ISSUE THREAD

**Issue by Xiuyi-Wang** [PennLINC/xcp_abcd#180]
Hello, Many thanks for developing this tool.

I would like to run the postprocessing using xcp_abcd.

The OS is Ubuntu 18.

The xcp_abcd version is

docker run -it pennlinc/xcp_abcd  --version
xcp_abcd v0.0.5+0.g35d429d.dirty

The following is my command:

export path_input=*/fmriprep
export path_output=directory_output
sub_ID=sub-01
docker run -it  -v ${path_input}:/data:ro    -v ${path_output}:/out pennlinc/xcp_abcd  /data   /out   \
participant  --participant_label   ${sub_ID} --cifti 

The error message is:

211028-02:42:27,713 nipype.workflow IMPORTANT:
	 
    Running xcp_abcd version 0.0.5+0.g35d429d.dirty:
      * fMRIPrep directory path: /data.
      * Participant list: ['02R4928'].
      * Run identifier: 20211028-024137_f0590b68-ae0e-45e2-9a04-cce29d2210e5.

    
211028-02:43:10,845 nipype.utils WARNING:
	 A newer version (1.7.0) of nipy/nipype is available. You are using 1.6.1
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/cli/run.py", line 456, in build_workflow
    retval['workflow'] = init_xcpabcd_wf (
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 146, in init_xcpabcd_wf
    single_subj_wf = init_subject_wf(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_abcd/workflow/base.py", line 343, in init_subject_wf
    DerivativesDataSink(base_directory=output_dir,source_file=subject_data[0][0],desc='summary', datatype="figures"),
IndexError: list index out of range

I do not know how to deal with this error. Many thanks.

Xiuyi

**Comment by Xiuyi-Wang** [comment]
Thanks. I sort it out. The problem is that some nifit files are missing because I did not choose them when running fMRIPrep.  When I run fMRIPrep, I only choose the cifti format and fsaverage template. But I read the source code, it says some nifti files, including *boldref.nii.gz, '*desc-brain_mask.nii.gz','*preproc_bold.nii.gz', are necessary even if I choose -cifti. If this info could be added to the usage page, that would be great. 

The following is the fMRIPrep command I used when I had this error. 
fmriprep-docker ${path_input} ${path_output} participant --participant-label ${sub_ID} --fs-license-file ${license_file}   --use-aroma   --cifti-output  --use-syn-sdc   --output-spaces  fsaverage:den-41k        >> ${path_output}/${sub_ID}_fMRIPrep_wb.txt

After I rerun the fMRIPrep command like this, it works:
fmriprep-docker ${path_input} ${path_output} participant --participant-label ${sub_ID} --fs-license-file ${license_file}   --use-aroma   --cifti-output  --use-syn-sdc   --output-spaces  fsaverage:den-41k    **MNI152NLin6Asym:res-2**   >> ${path_output}/${sub_ID}_fMRIPrep_wb.txt

Many thanks. 

Xiuyi
